add state
htmlacademy-react/441629-guess-melody-5 pull request #4
Opened 2020-10-06 19:28 UTC by Damir92

2020-10-06 20:13 UTC, rawle51 commented on src/components/genre-question-screen/genre-question-screen.jsx
> +            onAnswer(question, userAnswers);
метод стоит определить внутри компонента если он не используется данные из компонента родителя
здесь именно такой кейс
определение его выше по дереву только усложняется читаемость компонента

2020-10-06 20:13 UTC, rawle51 commented on src/components/genre-question-screen/genre-question-screen.jsx
> +  const [userAnswers, setUserAnswers] = useState([false, false, false, false]);
а если придут данные где 3 варианта ответа? или 2, или 6
вроде нет фиксированной величины
попробуй сделать универсально

2020-10-06 20:13 UTC, rawle51 commented on src/components/genre-question-screen/genre-question-screen.jsx
> +                      ...prevUserAnswers.slice(0, i), value, ...prevUserAnswers.slice(i + 1)
1) вынеси метод выше из разметки

2) не очень нравятся сложные калькуляции, можно на будущее подумать как упростить
возможно структуру ответа поменять на объект вместо массива, так будет запись быстрее
(это решение тоже рабочее, но если хочешь можно оптимизировать)

2020-10-06 20:13 UTC, rawle51 commented on src/components/genre-question-screen/genre-question-screen.jsx
> +  }).isRequired,
нечто подобное уже видел)
попробуй вынести в типы
и под каждый тип вопроса сформировать свой тип
а потом детализировать тип questins: array

2020-10-06 20:13 UTC, rawle51 commented on src/components/welcome-screen/welcome-screen.jsx
> +const WelcomeScreen = ({errorsCount, onPlayButtonClick}) => {
я бы определил метод внутри компонента

2020-10-07 13:04 UTC, Damir92 commented on src/components/genre-question-screen/genre-question-screen.jsx
> +            onAnswer(question, userAnswers);
Этот метод в компоненте GameScreen двигает шаг игры дальше, т.е. он общается с родителем

2020-10-07 17:22 UTC, rawle51 commented on src/components/app/app.jsx
> +          render={({history}) => (
Я имел ввиду что history доступно уже по дефолту, но ладно, пока так оставим

2020-10-07 17:24 UTC, rawle51 commented on src/components/artist-question-screen/artist-question-screen.jsx
> +const ArtistQuestionScreen = ({onAnswer, question}) => {
А тут что не добавил дефолтное значение?

2020-10-07 17:33 UTC, Damir92 commented on src/components/app/app.jsx
> +          render={({history}) => (
Не получилось сразу найти как по-другому использовать, поэтому прокинул через props

2020-10-07 17:34 UTC, Damir92 commented on src/components/artist-question-screen/artist-question-screen.jsx
> +const ArtistQuestionScreen = ({onAnswer, question}) => {
Похоже не сохранил когда коммитил

2020-10-07 17:53 UTC, rawle51 requested changes

2020-10-07 17:53 UTC, rawle51 commented on src/components/game-screen/game-screen.jsx
> +        <ArtistQuestionScreen
Вот тут ты можешь передать в question undefined
А в компоненте нет дефолтного значения 

Лишняя проверка не бывает лишней

2020-10-07 17:53 UTC, rawle51 commented on src/components/genre-question-screen/genre-question-screen.jsx
> +const GenreQuestionScreen = ({onAnswer, question}) => {
Тут опечатался question={}

2020-10-07 17:53 UTC, rawle51 commented on src/components/game-screen/game-screen.jsx
> +          question={question}
Тут аналогично - есть вероятность undefined и внутри компонента ты деструктуризируешь проп

2020-10-07 17:53 UTC, rawle51 commented on src/components/genre-question-screen/genre-question-screen.jsx
> +
Это прям не сильно проще
useState стоит держать максимально простым

Если нужно скалькулировать первоначальное значение - это стоит сделать до определения useState.

Структуру данных в данном случае не нужно предопределять заранее 
useState({})

setState(prev => ({ ...prev, [i]: value })

2020-10-07 17:53 UTC, rawle51 commented on src/components/genre-question-screen/genre-question-screen.jsx
> +
Таком образом если надо проставить чекбокс ты используешь Boolean(state[i]) - что по дефолту вернёт нужный тебе false

2020-10-08 10:46 UTC, rawle51 commented on src/components/game-screen/game-screen.jsx
> +  if (!questions || step >= questions.length || !question) {
два раза `!questions`
+ у тебя теперь по дефолту questions массив
смысла в проверке нет
и лучше questions.length > 0
step динамичная переменная и могут возникнуть баги и коллизии

2020-10-08 10:47 UTC, rawle51 commented on src/components/genre-question-screen/genre-question-screen.jsx
> +      return currUserAnswers;
setUserAnswers(prev => ({ ...prev, [i]: evt.target.checked })

2020-10-08 10:47 UTC, rawle51 commented on src/components/genre-question-screen/genre-question-screen.jsx
> +      return currUserAnswers;
`const handleInputChange = (evt, i) => setUserAnswers(prev => ({ ...prev, [i]: evt.target.checked })`

2020-10-08 11:46 UTC, merged